module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  asset: 0
  block: 0
  breakpoint: 0
  config_rewrite: 0
  consumers: 0
  csv_serialization: 0
  date_popup: 0
  dblog: 0
  entity: 0
  entity_browser: 0
  entity_reference_integrity: 0
  entity_reference_integrity_enforce: 0
  entity_reference_revisions: 0
  entity_reference_validators: 0
  exif_orientation: 0
  farm_activity: 0
  farm_animal: 0
  farm_api: 0
  farm_custom: 0
  farm_dashboard: 0
  farm_entity: 0
  farm_equipment: 0
  farm_field: 0
  farm_flag: 0
  farm_format: 0
  farm_harvest: 0
  farm_id_tag: 0
  farm_input: 0
  farm_land: 0
  farm_land_types: 0
  farm_location: 0
  farm_log: 0
  farm_log_category: 0
  farm_login: 0
  farm_maintenance: 0
  farm_map: 0
  farm_material: 0
  farm_observation: 0
  farm_plant: 0
  farm_quantity_standard: 0
  farm_role: 0
  farm_role_roles: 0
  farm_season: 0
  farm_seeding: 0
  farm_settings: 0
  farm_structure: 0
  farm_structure_types: 0
  farm_ui: 0
  farm_ui_action: 0
  farm_ui_breadcrumb: 0
  farm_ui_map: 0
  farm_ui_menu: 0
  farm_ui_theme: 0
  farm_ui_user: 0
  farm_ui_views: 0
  farm_unit: 0
  farm_water: 0
  field: 0
  file: 0
  filter: 0
  fraction: 0
  geofield: 0
  image: 0
  inline_entity_form: 0
  jsonapi: 0
  jsonapi_extras: 0
  jsonapi_schema: 0
  log: 0
  options: 0
  path_alias: 0
  quantity: 0
  rest: 0
  serialization: 0
  simple_oauth: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_geojson: 0
  views: 10
  farm: 1000
theme:
  claro: 0
  gin: 0
profile: farm
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
