preset_accent_color: green
preset_focus_color: orange
enable_darkmode: false
classic_toolbar: vertical
icon_default: false
icon_path: modules/custom/farm_custom/media/rooted_solutions_logo.png
high_contrast_mode: false
show_user_theme_settings: false
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: QdiqmcH9tjpstXqCQKv4G4rHYE4HjWLFkVzyqooqEWM
favicon:
  use_default: false
  path: profiles/farm/modules/ui/theme/favicon.ico
  mimetype: image/vnd.microsoft.icon
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
accent_color: ''
focus_color: ''
icon_upload: ''
