name: Build image

on:
  push:
    tags:
      - '2.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name.
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Get image name.
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository }}" >> $GITHUB_ENV
      -
        name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push image.
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          # Optionally provide secrets to the Dockerfile.
#          secrets: |
#            "github_access_token=${{ secrets.GH_ACCESS_TOKEN }}"
          tags: |
            ${{ env.IMAGE_NAME }}:2.x
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
